personal account button, README file
AndreyKhlestov/FeedMe pull request #17
Opened 2024-06-14 18:15 UTC by ZebraHr

2024-06-14 19:45 UTC, AndreyKhlestov requested changes

2024-06-14 19:45 UTC, AndreyKhlestov commented on README.md
> +Создайте виртуальное окружение:
можно не расписывать, как запускать проект локально, т.к. локально будут запускать редко и то, только разработчики, которые и так знают, как это делается и куда подсматривать.

Лучше расписать как запустить проект на сервере

2024-06-14 19:45 UTC, AndreyKhlestov commented on README.md
> +[![aiosqlite](https://img.shields.io/badge/PostgreSQL-blue)](https://www.postgresql.org/docs/)
опечатка. мы не используем aiosqlite

2024-06-14 19:45 UTC, AndreyKhlestov commented on README.md
> +В корне проекта создайте файл .env и поместите в него:
У нас был файл .env.template (в какой-то момент удалился). Лучше его снова добавить и все переменные прописать. В нем можно добавить некоторые подсказки. 
Таким образом и инструкция будет короче (переименуйюте файл ... и заполните необходимые поля) и разработчику будет проще (уже есть готовый файл, который осталось только переименовать и внести пару токенов)

2024-06-14 19:45 UTC, AndreyKhlestov commented on README.md
> +Закрываем подключение, чтобы не останавлиать контенеры и подключаемся снова к серверу;
а зачем нам перезаходить на сервер и заходить в контейнер django проекта?

2024-06-14 19:45 UTC, AndreyKhlestov commented on tg_bot/handlers/default.py
> +                url=f"http://127.0.0.1:8000/telegram/report/{message.from_user.id}/"
web upp позволяет переходить только по адресам, начинающимся с https.
Еще в env файле мы указываем адрес сервера (например fantastic-daifuku-040ed7.netlify.app)

таким образом можно сделать универсальную ссылку: https:// + адрес сервера + /telegram/receiving_report/{message.from_user.id}/

p.s. url немного поменялся (с report на receiving_report)

2024-06-14 19:45 UTC, AndreyKhlestov commented on tg_bot/handlers/default.py
> +    )  # url='https://fantastic-daifuku-040ed7.netlify.app/'
можно удалить лишний код

2024-06-14 19:47 UTC, ZebraHr commented on README.md
> +[![aiosqlite](https://img.shields.io/badge/PostgreSQL-blue)](https://www.postgresql.org/docs/)
Пропустила)))

2024-06-14 19:48 UTC, ZebraHr commented on README.md
> +В корне проекта создайте файл .env и поместите в него:
Ок

2024-06-15 11:28 UTC, AndreyKhlestov approved these changes

2024-06-15 11:32 UTC, merged