added loguru as logger
AndreyKhlestov/FeedMe pull request #7
Opened 2024-06-10 14:08 UTC by ZebraHr

в файле config.py строки 24-27 и 32-61 нужны исключительно, чтобы настроить цвет уровня логирования в терминале, в файле это автоматом происходит. Если цвет уровня в терминале не принципиален, можно код облегчить

2024-06-10 14:14 UTC, fabilya commented on requirements.txt
> +loguru==0.7.2
можно оставить только loguru, остальные зависимости установятся автоматически

2024-06-10 14:17 UTC, fabilya requested changes
оставил комментарии внутри

2024-06-10 14:27 UTC, fabilya approved these changes

2024-06-11 15:01 UTC, KonstantinSKS approved these changes

2024-06-12 05:35 UTC, AndreyKhlestov requested changes

2024-06-12 05:35 UTC, AndreyKhlestov commented on tg_bot/config.py
> +logger.add(
можно упростить код

```
log_formats = {
    "INFO": f" <blue>{{level}}</blue>{log_format_base}",
    "DEBUG": f" <cyan>{{level}}</cyan>{log_format_base}",
    "WARNING": f" <yellow>{{level}}</yellow>{log_format_base}",
    "ERROR": f" <red>{{level}}</red>{log_format_base}",
}

def create_filter(level):
    return lambda record: record["level"].name == level

for level, log_format in log_formats.items():
    logger.add(
        sys.stdout,
        format=log_format,
        level=level,
        filter=create_filter(level),
    )
```

2024-06-12 11:10 UTC, closed without merging